import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

ApplicationWindow {
    visible: true
    width: 1280; height: 800; minimumWidth: 980; minimumHeight: 640
    title: "Embervault Control Center"; color: "#0d0c14"
    property color ink: "#edeaf4"; property color muted: "#918da4"; property color panel: "#15141e"; property color line: "#2b2739"; property color ember: "#ef8b4d"
    property int page: 0

    RowLayout { anchors.fill: parent; spacing: 0
        Rectangle { Layout.fillHeight: true; Layout.preferredWidth: 248; color: "#100f18"; border.color: line; border.width: 1
            ColumnLayout { anchors.fill: parent; anchors.margins: 22; spacing: 12
                RowLayout { Layout.fillWidth: true; Text { text: "✦"; color: ember; font.pixelSize: 23 }; Column { Text { text: "EMBERVAULT"; color: ink; font.bold: true; font.pixelSize: 13; font.letterSpacing: 1.5 }; Text { text: "CONTROL CENTER"; color: muted; font.pixelSize: 10; font.letterSpacing: 1.1 } } }
                Rectangle { Layout.fillWidth: true; height: 1; color: line; Layout.topMargin: 18; Layout.bottomMargin: 10 }
                Text { text: "WORKSPACE"; color: muted; font.pixelSize: 10; font.letterSpacing: 1.4; Layout.bottomMargin: 4 }
                NavButton { label: "Home"; icon: "⌂"; pageIndex: 0 }; NavButton { label: "My Mods"; icon: "◈"; pageIndex: 1 }; NavButton { label: "Game Settings"; icon: "◌"; pageIndex: 2 }; NavButton { label: "Save Manager"; icon: "▣"; pageIndex: 3 }; NavButton { label: "Troubleshooter"; icon: "⌁"; pageIndex: 4 }
                Text { text: "TOOLS"; color: muted; font.pixelSize: 10; font.letterSpacing: 1.4; Layout.topMargin: 22; Layout.bottomMargin: 4 }
                NavButton { label: "Content Studio"; icon: "◇"; pageIndex: 5 }; NavButton { label: "Research Lab"; icon: "⌬"; badge: "Experimental"; pageIndex: 6 }; NavButton { label: "Knowledge"; icon: "?"; pageIndex: 7 }
                Item { Layout.fillHeight: true }; Rectangle { Layout.fillWidth: true; height: 1; color: line }; NavButton { label: "Settings"; icon: "⚙"; pageIndex: 8 }
                RowLayout { Text { text: "●"; color: "#83a77b"; font.pixelSize: 9 }; Text { text: "Core services ready"; color: muted; font.pixelSize: 11 } }
            }
        }
        ColumnLayout { Layout.fillWidth: true; Layout.fillHeight: true; spacing: 0
            Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 72; color: "#11101a"; border.color: line; Text { anchors.left: parent.left; anchors.leftMargin: 34; anchors.verticalCenter: parent.verticalCenter; text: page === 3 ? "Save Manager" : page === 0 ? "Home" : "Embervault"; color: ink; font.pixelSize: 20; font.bold: true }; RowLayout { anchors.right: parent.right; anchors.rightMargin: 34; anchors.verticalCenter: parent.verticalCenter; spacing: 18; ComboBox { model: controlCenter.profileOptions; currentIndex: 0; onActivated: controlCenter.selectProfile(currentIndex) }; Rectangle { width: 1; height: 22; color: line }; Text { text: "●  " + controlCenter.gameStatus; color: "#9ec18e"; font.pixelSize: 12 } } }
            StackLayout { currentIndex: page; Layout.fillWidth: true; Layout.fillHeight: true; HomePage {}; PlaceholderPage { heading: "My Mods"; body: "Package management will appear here after the module framework is connected." }; PlaceholderPage { heading: "Game Settings"; body: "Gameplay tuning will be added as an independently packaged module." }; SaveManagerPage {}; PlaceholderPage { heading: "Troubleshooter"; body: "Health scans will use Core logs, operations, compatibility, and module state." }; PlaceholderPage { heading: "Content Studio"; body: "Content creation remains a guarded developer preview." }; PlaceholderPage { heading: "Research Lab"; body: "Research runs in isolated profiles and records evidence before promotion." }; PlaceholderPage { heading: "Knowledge"; body: "Offline documentation will be linked from every module." }; PlaceholderPage { heading: "Settings"; body: "Application settings will be surfaced here." } }
        }
    }

    component NavButton: Rectangle { id: nav; property string label; property string icon; property string badge: ""; property int pageIndex; Layout.fillWidth: true; height: 40; radius: 7; color: page === pageIndex ? "#25202d" : "transparent"; border.color: page === pageIndex ? "#4c3940" : "transparent"; RowLayout { anchors.fill: parent; anchors.leftMargin: 12; anchors.rightMargin: 10; Text { text: nav.icon; color: page === nav.pageIndex ? ember : muted; font.pixelSize: 16; Layout.preferredWidth: 23 }; Text { text: nav.label; color: page === nav.pageIndex ? ink : "#aaa5b7"; font.pixelSize: 13 }; Item { Layout.fillWidth: true }; Text { text: nav.badge; color: muted; font.pixelSize: 9 } }; MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: page = nav.pageIndex } }
    component HomePage: ScrollView { clip: true; ColumnLayout { width: parent.width; spacing: 26; anchors.margins: 38; ColumnLayout { Layout.fillWidth: true; spacing: 8; Text { text: "Good evening, Joel"; color: ember; font.pixelSize: 11; font.letterSpacing: 1.4 }; Text { text: "Your worlds, under control."; color: ink; font.pixelSize: 34; font.bold: true }; Text { text: "Review your active profile, protect your saves, and pick up where you left off."; color: muted; font.pixelSize: 15 } }; RowLayout { Layout.fillWidth: true; spacing: 14; StatusCard { title: "GAME STATUS"; value: controlCenter.gameStatus; note: controlCenter.gameBuild; accent: "#83a77b" }; StatusCard { title: "ACTIVE PROFILE"; value: controlCenter.profileName; note: "Core profile"; accent: ember }; StatusCard { title: "SAFETY"; value: "Ready"; note: controlCenter.safetySummary + " · " + controlCenter.saveSummary; accent: "#d8b46a" } }; Text { text: "Continue"; color: ink; font.pixelSize: 17; font.bold: true }; ActionCard { title: "Open Save Manager"; description: "Inspect your saves or create a verified backup before testing."; action: "Open"; onTriggered: page = 3 }; ActionCard { title: "Review modules"; description: "See what is installed, compatible, or waiting for review."; action: "View modules"; onTriggered: page = 1 } } }
    component SaveManagerPage: ScrollView { clip: true; ColumnLayout { width: parent.width; spacing: 22; anchors.margins: 38; ColumnLayout { Layout.fillWidth: true; spacing: 8; Text { text: "SAVE SAFETY"; color: ember; font.pixelSize: 11; font.letterSpacing: 1.4 }; Text { text: "Protect before you experiment."; color: ink; font.pixelSize: 30; font.bold: true }; Text { text: "The first release inspects, backs up, verifies, previews, and restores. It does not edit save contents."; color: muted; font.pixelSize: 15; wrapMode: Text.WordWrap } }; Rectangle { Layout.fillWidth: true; height: 72; radius: 9; color: panel; border.color: line; RowLayout { anchors.fill: parent; anchors.margins: 18; Text { text: "▣"; color: ember; font.pixelSize: 23 }; ColumnLayout { Layout.fillWidth: true; Text { text: "Save directory"; color: ink; font.bold: true; font.pixelSize: 14 }; Text { text: "Choose a save folder to inspect and protect it."; color: muted; font.pixelSize: 11 } }; Button { text: "Choose folder"; onClicked: controlCenter.chooseSaveFolder() } } }; RowLayout { Layout.fillWidth: true; spacing: 14; StatusCard { title: "BACKUPS"; value: controlCenter.saveSummary; note: "Verified snapshots"; accent: "#d8b46a" }; StatusCard { title: "WRITE POLICY"; value: "Protected"; note: "No direct save editing"; accent: "#83a77b" } }; Rectangle { Layout.fillWidth: true; height: 168; radius: 9; color: panel; border.color: line; ColumnLayout { anchors.fill: parent; anchors.margins: 18; Text { text: "Safe restore"; color: muted; font.pixelSize: 10; font.letterSpacing: 1.2 }; RowLayout { ComboBox { Layout.fillWidth: true; model: controlCenter.backupOptions; onActivated: controlCenter.selectBackup(currentIndex) }; Button { text: "Preview"; enabled: controlCenter.backupOptions.length > 0; onClicked: controlCenter.previewRestore() }; Button { text: "Restore selected"; enabled: controlCenter.backupOptions.length > 0; onClicked: controlCenter.restoreSelected() } }; Text { text: controlCenter.restorePreview; color: muted; font.pixelSize: 11; wrapMode: Text.WordWrap; Layout.fillWidth: true }; RowLayout { Button { text: "Inspect"; onClicked: controlCenter.inspectSaves() }; Button { text: "Backup now"; enabled: controlCenter.canBackup; onClicked: controlCenter.createBackup("manual") }; Text { text: controlCenter.lastSaveMessage; color: muted; font.pixelSize: 11 } } } } } }
    component PlaceholderPage: ScrollView { property string heading; property string body; ColumnLayout { width: parent.width; anchors.margins: 38; spacing: 12; Text { text: heading; color: ink; font.pixelSize: 30; font.bold: true }; Text { text: body; color: muted; font.pixelSize: 15; wrapMode: Text.WordWrap; Layout.maximumWidth: 680 } } }
    component StatusCard: Rectangle { property string title; property string value; property string note; property color accent; Layout.fillWidth: true; height: 116; radius: 9; color: panel; border.color: line; Column { anchors.fill: parent; anchors.margins: 18; spacing: 7; Text { text: title; color: muted; font.pixelSize: 10; font.letterSpacing: 1.1 }; Text { text: value; color: accent; font.pixelSize: 22; font.bold: true }; Text { text: note; color: muted; font.pixelSize: 11 } } }
    component ActionCard: Rectangle { signal triggered(); property string title; property string description; property string action; Layout.fillWidth: true; height: 86; radius: 9; color: panel; border.color: line; RowLayout { anchors.fill: parent; anchors.margins: 17; Text { text: "✦"; color: ember; font.pixelSize: 21; Layout.preferredWidth: 32 }; ColumnLayout { Layout.fillWidth: true; Text { text: title; color: ink; font.pixelSize: 14; font.bold: true }; Text { text: description; color: muted; font.pixelSize: 11; wrapMode: Text.WordWrap; Layout.fillWidth: true } }; Button { text: action; flat: true; contentItem: Text { text: action; color: ember; font.pixelSize: 12 }; onClicked: triggered() } } }
}
